### ISSUE TITLE
Clarify uniqueness requirement for ECU identifiers.

### ISSUE THREAD

**Issue by mnm678** [uptane/deployment-considerations#106]
In the glossary, ECU identifiers are defined as "An attribute used to identify a specific ECU (e.g., a unique serial number)." What do these identifiers need to be unique across?

Proposal: change the above to state "A globally unique attribute..."

**Comment by jhdalek55** [comment]
This makes all makes sense. Any objections to merging?

**Comment by jhdalek55** [comment]
Closed via PR #108
