### ISSUE TITLE
Overwriting the changelog

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#107]
This is a purely mechanical question, but I wanted to clarify something discussed in the 5-11 meeting. Sometime next month, I will be writing the changelog for V 1.2.0. That means adding text that will only document changes made between med-January 2021 and June 30 of the same year. The consensus was that it would be all right to remove the current changelog and have only the new text present since the original text would still be maintained in the PDF and HTML versions posted on the site. However, since the same text serves the pages on the website, access on the site will be limited to just the most recent changes.

It could be that this is not an issue at all. Maybe there is no need for a master document that logs all significant changes in the Standard. But, I felt the issue needed to be raised before I remove the current text.

I would like feedback on this before I have to do the edits, which means within the next week or two.

Thanks.

**Comment by pattivacek** [comment]
Why would we want to remove the older entries of the changelog? I think it's worth keeping those around somewhere. I see two solutions based on your comments:

1. Have one changelog doc with multiple sections, one for each new version, similar to the [aktualizr changelog](https://github.com/uptane/aktualizr/blob/master/CHANGELOG.md).
2. Have two documents, one only for the changes in the latest version, and another for the historical changes.

I'd say the choice between those options is dependent mostly upon what makes building the PDF and HTML easier.

**Comment by jhdalek55** [comment]
I think I like the second suggestion made by  @pattivacek, but I agree that how it affects building the PDF and HTML versions should be the most important consideration. Can someone who knows more than me weigh in on this?

**Comment by jhdalek55** [comment]
In the 5/25 Uptane meeting, the decision was made not to overwrite the changelog but to keep it as a running list in both the document and the webpages. With this decision made, we can close this issue.
