### ISSUE TITLE
Should the primary send the Director's targets metadata to all secondaries, even those for which there is no target?

### ISSUE THREAD

**Issue by cchalm** [uptane/deployment-considerations#134]
Consider a vehicle with the following architecture:

- Primary ECU "A"
- Secondary ECU "B"
- Secondary ECU "C"
```
    A
   / \
  B   C
```

If the primary ECU receives targets metadata from the director that contains a target for B but not for C, should/must the targets metadata still be sent to C for verification?

If the primary ECU receives targets metadata from the director that is empty, i.e. lists no targets for any ECU, should/must the targets metadata still be sent to B and C for verification?

Previous discussions have revealed a couple points of consideration:
- Would giving the primary the authority to decide whether to send the targets metadata to the secondary allow a malicious primary to silently deny updates to secondaries in a way it wouldn't be able to otherwise?
- Is there any other information in the metadata that a secondary needs to verify even if there are no targets, e.g. for continuity? Can a secondary skip a targets metadata and still have all the information it needs to verify the next one?

**Comment by pattivacek** [comment]
> If the primary ECU receives targets metadata from the director that contains a target for B but not for C, should/must the targets metadata still be sent to C for verification?

IMO no. What would be the benefit?

> If the primary ECU receives targets metadata from the director that is empty, i.e. lists no targets for any ECU, should/must the targets metadata still be sent to B and C for verification?

Again no, what's the point?

> * Would giving the primary the authority to decide whether to send the targets metadata to the secondary allow a malicious primary to silently deny updates to secondaries in a way it wouldn't be able to otherwise?

Yes, but the Primary has that authority regardless. How would a Secondary recognize that a Primary isn't sending it new metadata? AFAICT that isn't possible in the current standard. We could change that to require that the Primary sends the latest metadata to each Secondary every x amount of time, but that sounds like a lot of redundant communication, and the Secondary would still not know how to trust the Primary.

> * Is there any other information in the metadata that a secondary needs to verify even if there are no targets, e.g. for continuity?

IMO no, what would the benefit be?

> Can a secondary skip a targets metadata and still have all the information it needs to verify the next one?

Yes, as long as the Root metadata hasn't expired. The Primary should be obligated to send new metadata if that happens.

**Comment by cchalm** [comment]
Regarding continuity, I was paraphrasing a concern raised by members of the Uptane group during initial discussion of this question, so I'm hoping someone involved in the conception of that concern will chime in. Until then I'll just respond with regard to capabilities of a malicious primary.

While a malicious primary can, of course, choose not to send information to secondaries, it cannot prevent the secondaries from tattling to the Director about it via their version reports. We could, for instance, choose to require each version report to include the version number of the last targets metadata the secondary received and verified. The Director could use this information to determine whether the primary is distributing the required information to its secondaries.

Then again, one might argue that since the Director already has the ability to determine whether the primary has denied knowledge of a required update to a secondary (by checking whether the next version report from that secondary indicates that it installed the desired target), there is no additional value in determining whether the primary has denied the targets metadata to a secondary for which there was no target listed.

**Comment by pattivacek** [comment]
> We could, for instance, choose to require each version report to include the version number of the last targets metadata the secondary received and verified. The Director could use this information to determine whether the primary is distributing the required information to its secondaries.

That is interesting. It is extra information that the Secondary would have to store (so perhaps impractical for partial verification Secondaries), but I like the idea.

> since the Director already has the ability to determine whether the primary has denied knowledge of a required update to a secondary (by checking whether the next version report from that secondary indicates that it installed the desired target), there is no additional value in determining whether the primary has denied the targets metadata to a secondary for which there was no target listed.

Right. I'm skeptical that that effort (sending empty/irrelevant Targets metadata to a Secondary) would be worth the rather small benefit (maybe detecting an attack slightly faster), but I'd be happy to hear dissenting voices. I haven't thought this through _that_ thoroughly.

**Comment by jhdalek55** [comment]
Just to inject some of the discussion we had on this issue, I think the concern was if we don't require that the Primary send the Targets metadata to the ECU for verification, even when there is no image and no Targets metadata, we might be ignoring updates in the Root, Timestamp or Snapshot metadata that would still need to be verified. As written up in the notes from the first time it was discussed, "As this (eliminating the verification step with empty Targets) could have security implications, we are leaning towards strongly affirming the need to continue this requirement. To resolve this issue, we feel the proposed scenario being suggested needs some clarification, to perhaps only permit this step to be skipped if it is known that no **updates at all** are required at a given time."  @plapczyn or @JustinCappos or @tkfu ...as I believe you were part of this discussion, can you confirm if this was the concern?

**Comment by JustinCappos** [comment]
This matches my recollection as well.

**Comment by cchalm** [comment]
> we might be ignoring updates in the Root, Timestamp or Snapshot metadata that would still need to be verified.

Missing a version of Targets, Snapshot, or Timestamp metadata does not prevent verification of the following version, does it? E.g. an ECU can verify Timestamp metadata v10 if the last version it saw was v1. Why would a secondary ECU missing a version of these metadatas be a problem?

Verifying Root metadata does not require Targets metadata, so how would denying Targets metadata to a secondary cause it to miss a Root metadata update?

**Comment by JustinCappos** [comment]
Uptane can usually validate files from a later version in the situations
you describe.  For targets, snapshot, or timestamp, there usually isn't a
problem.

Verifying Root metadata does not require Targets metadata, so how would
> denying Targets metadata to a secondary cause it to miss a Root metadata
> update?


The issue here is that there is no requirement to send updated root
metadata, etc. when it has changed if there is not also a targets file
update.

So, consider the case where a full verification secondary ECU does not
receive root updates over an extended period (because it has not been
pushed an update), that secondary may be unable to update.  It may also
trust outdated keys that have been compromised for an extended period of
time.

Situations like this are what we are trying to address.

**Comment by cchalm** [comment]
You're assuming that a secondary ECU can only rotate Root metadata when the primary ECU does, but nothing that I've read in the standard prevents secondaries from doing this later. E.g. if a secondary could request specific versions of Root metadata from the primary, with the primary acting as a proxy to the Director, it could rotate to the latest root metadata at any time.

**Comment by pattivacek** [comment]
The context is clearer to me, but AFAICT this has nothing to do with Targets metadata; the issue is Root metadata. There are two cases I'm aware of:

1. Secondary is not capable of updating Root metadata itself (the minimal partial verification case): the Primary will need to push an update to the Secondary with the new Root metadata embedded in it. The image creator, Director, and Primary are responsible for making sure this happens.
2. Secondary can update Root metadata (full verification and perhaps some partial verification cases): the Primary should be responsible for pushing the metadata to the Secondary when it changes.

In both cases, this should happen before the previous Root expires. None of this involves Targets metadata; that's a separate matter.

> The issue here is that there is no requirement to send updated root metadata, etc. when it has changed if there is not also a targets file update.

I think this is already reasonably well described in [5.4.2.6. Send metadata to Secondaries](https://uptane.github.io/uptane-standard/uptane-standard.html#send_metadata_primary), for example, "The metadata it sends to each Secondary SHALL include all of the metadata required for verification on that Secondary." I don't see the limitation about Targets metadata. If something in the Deployment doc disagrees, then we should rectify that, but as I read it, the Standard covers this just fine.

**Comment by tkfu** [comment]
I think @pattivacek's answer here is pretty definitive. This discussion did lead to an interesting secondary discussion of renewing image repo root metadata in the absence of new updates, however. That discussion has been opened as #136.

**Comment by pattivacek** [comment]
> The question we started with was:
> 
> > Should the primary send the Director's targets metadata to all secondaries, even those for which there is no target?
> 
> It seems that the answer we've arrived at is "no". If that's a correct interpretation of this discussion, I suggest that the following line in the standard from [5.4.2.6. Send metadata to Secondaries](https://uptane.github.io/uptane-standard/uptane-standard.html#send_metadata_primary), immediately prior to the line that @pattivacek quoted, be clarified:
> 
> > The Primary SHALL send its latest downloaded metadata to all of its associated Secondaries.
> 
> It doesn't say "some of its latest downloaded metadata" or anything like that, so it implies "ALL of its latest downloaded metadata". If the next sentence is meant to loosen the requirement to just the relevant subset of the downloaded metadata, then I think the first sentence should be softened to avoid a contradiction.

I believe the answer is "no" but if someone has a concern about a case in which the answer is something else, we should still talk that out.

I think your request for clarification in the Standard is fair. Would you like to make a proposal?

**Comment by jhdalek55** [comment]
@cchalm. Yes, please submit a PR to modify the line in question.

**Comment by cchalm** [comment]
New input from @iramcdonald. Quoting from https://github.com/uptane/uptane-standard/pull/240#issuecomment-1255435864:

> Speaking from a higher architectural perspective, I would be content if we say it is RECOMMENDED (i.e., SHOULD) for the Primary to simply always share all recent/relevant targets metadata with all Secondaries.
I'm not at all happy with this dubious optimization of not sending to some of the Secondaries.  That opens the door for security corner cases.

Should we re-open this issue to continue the discussion?

**Comment by pattivacek** [comment]
> Should we re-open this issue to continue the discussion?

As I last wrote here:

> I believe the answer is "no" but if someone has a concern about a case in which the answer is something else, we should still talk that out.

I've yet to hear such a case. If someone can imagine one, I'd like to hear it.

**Comment by iramcdonald** [comment]
Hi,

Well I concede that we can leave the issue closed.

I do feel that depending on the Primary to make the "optimized" decision
about which
Secondaries should get updated targets metadata feels fragile to me.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Can we bring this to a resolution?

**Comment by jhdalek55** [comment]
At the Uptane Standards call on 9/27 we agreed to refrain from making changes at this point. It may be worth discussing as part of the wider topic about metadata in the future.
