### ISSUE TITLE
Vehicles can't update Image repository root metadata unless and until they receive a software update to at least one ECU

### ISSUE THREAD

**Issue by tkfu** [uptane/deployment-considerations#136]
Consider the case where you want to perform a root key rotation for Image repo root metadata, for example because there is evidence that one or more keys may have been compromised. In this scenario, we'd want all ECUs to get the updated root metadata as soon as possible. However, there's an impediment to that happening: a vehicle will only check for new Image repository root metadata if Director targets metadata indicates that it has at least one updated image to install.

[Uptane Standard section 5.4.4.2, step 6](https://uptane.github.io/uptane-standard/uptane-standard.html#full_verification):
> If the Targets metadata from the Directory repository indicates that there are no new targets that are not already currently installed, the verification process SHALL be stopped and considered complete. Otherwise, download and check the Root metadata file from the Image repository, following the procedure in [Section 5.4.4.3](https://uptane.github.io/uptane-standard/uptane-standard.html#check_root).

Note that this is a **SHALL**: it is not permissible to check for updated image repo root metadata unless there is an image to be installed.

**Comment by tkfu** [comment]
We discussed this issue on the 30.08.2022 standards committee call, and agreed that there are two steps we should take here:

1. Add some text to deployment considerations about what to do when you need to rotate an Image repo root key. If you want your vehicles to get the metadata, you need to send out an update to at least one ECU, even if it's a "dummy" update that just bumps a version number.
2. We should relax this SHALL into a SHOULD in a future revision of the standard. Because this is a relaxation of constraints, as opposed to an imposition of a new constraint, we can do it in a minor release. Relaxing it to a SHOULD will allow implementors to order vehicles to check image repo root metadata when desirable, even in the absence of an update.

**Comment by pattivacek** [comment]
Ah interesting, I didn't think about this case specifically when considering https://github.com/uptane/deployment-considerations/issues/134. I agree on these steps, although we might want to add some text in the Standard itself to explain this, or at least provide it as an example of why you might want to send more metadata than appears necessary at first glance.

**Comment by jhdalek55** [comment]
I think what remains to be done here is to decide if we want to act on @pattivacek suggestion about adding a mention of why we "might want to send more metadata than appears necessary at first glance." The other revisions have been done.

**Comment by pattivacek** [comment]
> Or should we just leave this issue open with a Milestone marker of 3.0.0 and a note to make the change when we are ready to publish the new version?

That's probably easiest.

**Comment by jhdalek55** [comment]
Go ahead and make it a should for 2.1.

**Comment by jhdalek55** [comment]
See Standard PR #246

**Comment by jhdalek55** [comment]
With the merging of Standard PR #246 and Deployment Issue #142, I believe we can close this. @tkfu and @pattivacek, do you agree?

**Comment by pattivacek** [comment]
Yeah, LGTM, thanks!

**Comment by jhdalek55** [comment]
Closed on 2/28
