### ISSUE TITLE
Chicken-and-egg problem with Director Root metadata verification and latest time verification

### ISSUE THREAD

**Issue by cchalm** [uptane/deployment-considerations#137]
From https://uptane.github.io/deployment-considerations/repositories.html#changes-to-the-director-repository:
> If an external time source is in use, a representation of its public key is CONDITIONALLY REQUIRED in Director repository Root metadata.

If the public key for an external time source is specified in the Director Root metadata, then having a verified copy of the latest Director Root metadata is required to verify the time. Verifying the Director Root metadata requires checking that it has not expired, which requires a verified time. In short:
- Can't verify the time without the Director Root metadata
- Can't verify the Director Root metadata without the time

How should this cycle be broken?

**Comment by jhdalek55** [comment]
This was briefly discussed in the 12/6 . @mnm678 noted that TUF provides a solution to this issue via an option codified in https://github.com/theupdateframework/specification/commit/e645837a6a47113090d7fcd2a67172b3bf732d25  that "introduces a fixed notion of time for the duration of the client update workflow, bounded by an application defined maximum duration for the update. It is further recommended that the maximum duration is set to the same time period at
which the repository re-signs the timestamp metadata." A pull request that mentions how this works for TUF would resolve this issue.

**Comment by mnm678** [comment]
The problem with a secure source of time and root metadata is actually already addressed by the standard. In the [How to check Root metadata](https://uptane.github.io/papers/uptane-standard.2.0.0.html#rfc.section.5.4.4.3) section, it specifies that root metadata will be updated before the time is checked. While a compromised root would be able to perform a freeze attack, a compromise of root can do much worse and is out of scope of the standard. 

The TUF issue is a related issue about the time for the update as a whole, which we should discuss as part of bringing TUF and Uptane into alignment.

**Comment by jhdalek55** [comment]
@mnm678 or someone, can you address the comments above.

**Comment by mnm678** [comment]
There are two parts to this: a short-term and long-term way to handle it.

The attack mentioned here only works if timeserver is compromised for a long period of time. The vehicle will look for new root metadata and check expiration on each update cycle, so whenever the timeserver is recovered, this attack would be ended. 

Further, the timeserver setup in the deployment considerations is a suggestion, and will soon be replaced with international standards for time servers (NTP v5), which will be finalized soon and have a separate root of trust for the time server.

**Comment by jhdalek55** [comment]
Consider this for 2.2.

**Comment by cchalm** [comment]
> ...whenever the timeserver is recovered, this attack would be ended.

In a situation where an attacker has the timeserver private key, recovering the timeserver requires rotating the timeserver key, which requires updating root metadata. If the attacker also has middleman access sufficient to spoof a "no root metadata version N+1" response to vehicles, they can prevent the timeserver key rotation indefinitely. In other words, the attacker can make it impossible to recover the timeserver.

For the long-term solution, I'm curious to know how the separate root of trust will itself avoid this cyclic verification issue. It seems like a secure source of time must derive trust in a way that doesn't rely on time, otherwise it will always hit this problem.

**Comment by mnm678** [comment]
It is only unrecoverable as long as the attacker has MitM access as well as the timeserver key. If control over the network is re-established the original owner of the timeserver key could distribute the correct timestamp.

For the long-term solution, the idea is to use a root of trust outside of Uptane, as decided on by the standards groups working on NTP v5. This would then provide a source of time that is outside of Uptane, and not subject to the tradeoff you describe here.

**Comment by jhdalek55** [comment]
This has tentatively been slated for 2.2.0, but I'm assuming that is to resolve the larger issues connected to NTP v.5. But can we better clarify that the attack mentioned above is only a real threat if the the vehicle is offline for an extended amount of time and if  the attacker has MitM access as well as the timeserver key. Can we resolve at least this much for V.2.1.0

**Comment by cchalm** [comment]
It occurs to me now that the attacker capabilities I mentioned in my comments above (sign+serve malicious timeserver responses and deny the existence of Root metadata N+1) are sufficient to perpetually deny Root metadata rotation regardless of the cyclic verification problem in the title.

While the abstract problem (document contains information used to verify itself) still concerns me, I can't think of any specific attacks this expiration verification process would enable.

**Comment by jhdalek55** [comment]
Close this for now. Make sure though that the secure time problem is still an open question.

**Comment by jhdalek55** [comment]
Closing this with the opening of Issue #149
