### ISSUE TITLE
Reference to Map File

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#25]
On the Customization page, there are two references to the Map File. I know this was removed from the Standard (I did a search of the Standard, just to be sure and it is not referred to at all). We need a patch for that page that clarifies the procedure without the Map File.

**Comment by patrickvacek** [comment]
Are you referring to the repository mapping metadata? That's definitely [in the standard](https://uptane.github.io/uptane-standard/uptane-standard.html#repo_mapping_meta); it was mostly added in https://github.com/uptane/uptane-standard/pull/111.

**Comment by jhdalek55** [comment]
No this is an an explicit reference to the "map file"...under that terminology. I could not find a reference to the "map file" as a distinct component.

**Comment by jhdalek55** [comment]
Ok. I believe this is a terminology issue and not a change in technique. I'll take down this issue once I've correctly resolved the text.

**Comment by jhdalek55** [comment]
I'm closing this down as this is not the issue I thought it was. A simple wording change on PR #23 will resolve the problem.
