### ISSUE TITLE
On the dangers of dynamic directions

### ISSUE THREAD

**Issue by trishankatdatadog** [uptane/deployment-considerations#31]
We should discuss [dynamic directions](https://github.com/uptane/deployment-considerations/pull/23#issuecomment-547039349) in more depth. In particular, we say that it can be done, but also that it's dangerous, so proceed with caution.

This is not enough. We need to discuss risk-mitigating strategies in more detail. It's best to recommend nothing than to recommend something accidentally dangerous.

**Comment by jhdalek55** [comment]
Ok. Thanks for posting this. In the meantime, should we remove that text from the page? If its that big a concern, would it  not be better to take it down till this is resolved?

Lois

**Comment by jhdalek55** [comment]
@trishankatdatadog ...so we can move forward with this issue, could you outline a few of your specific concerns on this topic? That way, someone else could carry this forward if you don't have the time to do so? Thanks.

**Comment by trishankatdatadog** [comment]
I just looked at the [text](https://github.com/uptane/deployment-considerations/blob/59f8b1adc4f30ee4a3cc2620c527aee8b4c25803/customizations.md#picking-an-option-efficiency-vs-security), and the warning about efficiency vs security seems fine.

However, now I have questions about the efficiency concerns in there. I'll raise a separate issue.
