### ISSUE TITLE
Fetching the Root metadata in partial verification Secondaries

### ISSUE THREAD

**Issue by patrickvacek** [uptane/deployment-considerations#40]
As discussed in yesterday's call, there may still be a reasonable use case for a partial verification Secondary to fetch both the Root and Targets metadata from the Director (via the Primary), as opposed to only fetching the Targets and expecting the Root metadata to be baked into the image.

The problem with baking in the Root metadata is that a new image is required to update the Root metadata. This can be avoided by fetching it just like Targets metadata. This requires some additional logic to handle root rotations, but the logic is fairly straightforward, so the cost is not high.

Is there any reason that this wouldn't be viable? Or should we add a section to the deployment considerations (or the Standard) to describe this option?

This conversation branched out from the discussion of https://github.com/uptane/uptane-standard/pull/154.

**Comment by tkfu** [comment]
Closed by #42
