### ISSUE TITLE
We should maintain a stable PDF version of the Deployment pages

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#41]
On our 1/21 phone call there was some discussion over whether there was a need for a stable PDF version of the Deployment pages. Ira McDonald stated that OEMs have asked for such a document, and so we may want to consider adding a link to such a document. We would like to hear from the community if we should go ahead an implement this.

Ira, feel free to build on this.

**Comment by tkfu** [comment]
On the 18.02.2020 standards call, we agreed that we would release versioned deployment docs.

I will create a script or pipeline to generate a PDF from a particular commit, so that we can use the PDF as the specifically versioned recommendations.

**Comment by jhdalek55** [comment]
@tkfu Does this issue need to remain open, particularly now that you have set up a mechanism to do this?

**Comment by tkfu** [comment]
Ah, you’re absolutely right. Thanks for catching this, closed by #91
