### ISSUE TITLE
Examining the implications of  Time Server key compromise

### ISSUE THREAD

**Issue by allen-cain-tm** [uptane/deployment-considerations#45]
The Deployment Considerations gives an overview of a "Secure Source of Time" with more details on the "Time Server", including effects to the vehicle when needing to update the Time Server key.
Additionally, the Deployment Considerations discusses how to handle Key Compromise for Uptane-related Repo's & ECU keys.

Considering this, I believe there is a gap in discussing the effects of a Time Server key compromise, and what considerations an implementer/adopter should take into account.
For example, the compromise of the Time Server can result in an attacker performing a Fast-Forward attack (i.e., provide all vehicles a time in the very-far future).
Thus, _potentially_ performing a DOS for vehicles to update their metadata, since it will appear to be very old compared to the "maliciously attested" time.

<ins>**Proposal:**</ins> Suggest adding a paragraph considering the implications of the compromise of a Time Server key.

**Comment by jhdalek55** [comment]
It was agreed in the 9/1/20 meeting that this issue should be held for V.2.0.0 of Deployment Best Practices

**Comment by jhdalek55** [comment]
In the 12/22 meeting it was suggested we separate this into two issues. Adding a paragraph that describes the consequences of a Time Server key compromise simply requires a thoughtful description and could be marked for Version 1.2.0. The larger issue of "other methods in which an implementer may decide to determine if metadata is malicious or not, outside of the requirement of time" is more complicated and should be flagged for 2.0.0./

**Comment by jhdalek55** [comment]
Per my comments earlier this month, and our discussion on 12/22, I am adding a new Issue to address the larger "other methods" issue. Could someone remove those comments from this issue.

**Comment by jhdalek55** [comment]
We need a volunteer to draft this description. If you have addressed this issue in one of our previous papers, can someone flag the appropriate sections?

**Comment by jhdalek55** [comment]
Once again asking if someone can provide starter text for this.

**Comment by mnm678** [comment]
@trishankatdatadog Do you know of a previous document that described this? If not I'm happy to draft something.

**Comment by jhdalek55** [comment]
Closed with PR #101
