### ISSUE TITLE
Options for providing current time

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#5]
One very significant decision during the writing of the Uptane Standards was to not stipulate a particular way to deal with issues of time, due to the various approaches used in practice. What alternative approaches to providing current time do we need to accommodate?

**Comment by jhdalek55** [comment]
For background on this issue, please see closed issues #52 and #66 on the Standards Repository. We still need a volunteer to do an initial draft of a pull request to deal with this issue.

**Comment by zabbal** [comment]
https://github.com/uptane/uptane-standard/issues/52
https://github.com/uptane/uptane-standard/issues/66
just to make it easier :)

**Comment by patrickvacek** [comment]
> What alternative approaches to providing current time do we need to accommodate?

Sounds like Ira's comment [here](https://github.com/uptane/uptane-standard/issues/143#issuecomment-536800994) has some information worth incorporating to make sure we stay future-proof.

**Comment by jhdalek55** [comment]
Per phone meeting on 10/29, this issue will be closed for now. We can re-visit it as we move forward if it becomes clear there is a need to do so.
