### ISSUE TITLE
Deployment Considerations Clarifications

### ISSUE THREAD

**Issue by allen-cain** [uptane/deployment-considerations#51]
In Deployment Considerations section > Secure Time Source > Changes to all ECUs  - states the following: `At build time, ECUs will receive an attestation of the current time as downloaded from the Time Server.`.

Two points.
1) What is the definition of `build time` -- build code, ECU assembly, vehicle assembly, port, dealer?
2) If ECUs must receive an attestation of the current time, then this seems to conflict with the Standard Section 5.4.2.5, which allows for a Secondary to <ins>not</ins> receive the latest attested time due to `not [having] the capacity to verify a time message`.

<ins>**Proposals:**</ins>
1) Clarify the definition of build time to an assumed state of the ECU / Vehicle -- e.g., `after the vehicle has been assembled` 
2) Modify the Deployment Considerations to the following: `After the vehicle has been assembled, ECUs **may** receive an attestation of the current time as downloaded from the Time Server.`

**Comment by jhdalek55** [comment]
Closed via merging of PR #52
