### ISSUE TITLE
Setting up a FAQs page 

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#53]
In reference to issue #48, it was agreed we should add an FAQ page to v. 1.1.0 of the Deployment Considerations. In addition to Issue #48, are there other issues that we would like to acknowledge, but at this point, would not like to incorporate into the text of the Deployment  Document?

**Comment by jhdalek55** [comment]
It would be odd to have an FAQ for one item, so it would be good to identify a few other issues for this page. Are there issues we closed or deferred that could be referenced this way?

**Comment by jhdalek55** [comment]
Per our 10/27 meeting, we will be adding this page to V.1.1.0 of the Deployment document. In addition to a response to Issue #48, we will include a brief summary of "What makes Uptane different?" and "How does Uptane work with other protocols?." Answering the latter question may also require adding  some text to the "Customizing Uptane"

**Comment by jhdalek55** [comment]
@JustinCappos ...just a reminder . on the 10-27 call you offered to script some text for the two questions above. I am going to attempt an item based of answering Issue #48.

**Comment by patrickvacek** [comment]
This can be closed now that https://github.com/uptane/deployment-considerations/pull/59 is done.
