### ISSUE TITLE
Summarizing Main Changes from V.1.0.0

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#54]
As per @iramcdonald, our versioned pdf of Deployment Best Practices requires a summary of the primary changes. I am opening this issue as a gathering place for what should be mentioned in this write-up.

The basis of this document will be the commits made between August 2019 and September 2020. A list through June 2020 already exists at https://groups.google.com/g/uptane-standards/c/Vq8T9K9CHkM.

If someone wants to volunteer for this task, please use this issue to do so. Otherwise, I will provide draft text in a pull request that can be reviewed by the community. 

I will aim to submit a pull request with this copy within the next two weeks.

**Comment by jhdalek55** [comment]
I will work on this list next week. However, I'm not sure if I know how to open a new page for this content. @tkfu or @patrickvacek, could you open a markdown page for  "Changes Since V.1.0.0" and another for the FAQ page?

**Comment by patrickvacek** [comment]
> could you open a markdown page for "Changes Since V.1.0.0" and another for the FAQ page?

Sure, see https://github.com/uptane/deployment-considerations/pull/56. I don't have write privileges here so I had to make the PR from my fork. Up to you if you want to pull my branch and work on that or merge mine and make a new PR.

**Comment by jhdalek55** [comment]
Closed via Pull Request #57
