### ISSUE TITLE
Dealing with aftermarket ECU swaps

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#6]
All use cases in the Standard are based on the assumption that actions are initiated by an OEM. There’s a need to consider a use case for when one ECU is swapped for another at a dealer aftermarket. How do we correct for use cases that are not initiated by an OEM?

**Comment by jhdalek55** [comment]
Addressed in PR#17 @tkfu, can we close this issue now?

**Comment by tkfu** [comment]
Yup, closed by #17,
