### ISSUE TITLE
Housekeeping issue-Where to put "A JDF Project, etc."

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#64]
I don't know if this is even worth bothering with, which is why I am putting it as an issue, rather than making a pull request and submitting a change. The README for Deployment does not include a statement that Uptane is a JDF Project, such as what appears in the footer.

Uptane is a Joint Development Foundation project of the Linux Foundation, operating under the formal title of Joint Development Foundation Projects, LLC, Uptane Series. For questions about the documentation or implementation, please contact Prof. Justin Cappos and other members of the Secure Systems Lab at New York University. Contributors and maintainers are governed by the CNCF Community Code of Conduct.

Since I'm assuming the footer copy of the website will not be part of the completed PDF, this statement about our relationship to JDF must appear somewhere. Should I do a pull request to add it here, or should this be incorporated on the title page of the document?

**Comment by patrickvacek** [comment]
> The README for Deployment does not include a statement that Uptane is a JDF Project, such as what appears in the footer.

Good point.

> Since I'm assuming the footer copy of the website will not be part of the completed PDF, this statement about our relationship to JDF must appear somewhere.

Not 100% sure there, it might depend on how we build it.

> Should I do a pull request to add it here

I think it wouldn't hurt to put it in the README. It might also belong in `index.md`. I'd be fine with either or both.

**Comment by jhdalek55** [comment]
Ok. I agree it really needs to be in the document, so I'll put it in the README for now. When we get to the point of assembling the document we can always move it to another location.

**Comment by jhdalek55** [comment]
Note we will need to find a place for this information in the Deployment Best Practices. I am going to see if JDF has a "style sheet" for its publications, which will probably show where in the front matter this affiliation should grow.

**Comment by jhdalek55** [comment]
This issue was posted more as a reminder to include this mention somewhere in the versioned Deployment document. I don't think it needs to stay open. I'll leave it up for a few days and then will merge.
