### ISSUE TITLE
Authentication language

### ISSUE THREAD

**Issue by pattivacek** [uptane/deployment-considerations#76]
In the "Private API to update images and the inventory database" subsection of the "What the OEM should do" section of the [repositories page](https://uptane.github.io/deployment-considerations/repositories.html), we write that "[t]he OEM is free to use any authentication method, as long as it is suitably strong, such as client certificates, or two-factor authentication, such as a username coupled with a password, or an API key encrypted over TLS."

Does that sentence make sense to you? The two uses of "such as" really throw me for a loop. Also, username/password auth is not what I would consider two-factor authentication. Or am I missing something there?

**Comment by jhdalek55** [comment]
Yeah. The repetition of "such as" is ugly. Likely in the midst of editing that got inserted in the wrong place. I'm happy to fix that. 
Your second statement is better answered by someone else, though I agree it doesn't sound like what I know as two factor authentication.

**Comment by mnm678** [comment]
That sentence is pretty confusing. I agree that username/password is not two-factor authentication (but it could be one of the two factors). When we re-write this, maybe we can separate the two-factor part into it's own sentence, something like "the OEM is free to use any authentication method as long as it is suitably strong. Examples include client certifications, a  password, or an API key encrypted over TLS. For additional security, the OEM may use two-factor authentication that utilizes more than one authentication method."

**Comment by jhdalek55** [comment]
@mnm678 Your suggestion sounds perfect. Can you submit the sentence you just crafted as a suggestion?

**Comment by jhdalek55** [comment]
Actually I guess submit it as a PR.
