### ISSUE TITLE
Link to the Timestamp metadata

### ISSUE THREAD

**Issue by pattivacek** [uptane/deployment-considerations#77]
In several parts of the Director subsection of the "What the OEM should do" section of the [repositories page](https://uptane.github.io/deployment-considerations/repositories.html), we suggest things like that the Primary will "receive a link to a Timestamp metadata file in return" to sending a vehicle version manifest. I don't believe that this link is mentioned in the Standard. Is there any reason not to use a static location for the Timestamp metadata? I suppose it can be provided dynamically, but I think we should make it more clear that that is optional.

**Comment by pattivacek** [comment]
This is difficult to fix because an image (`assets/images/repo_4_primarytodirector.png`) also uses this text. I think we should maybe push this to the next release since it requires more effort than I can do today.

@mnm678 suggested that this language is probably from interoperability with TAP 5, which [we've now removed](https://github.com/uptane/uptane-standard/pull/196). Is that language still relevant for TAP 13? Either way, I think we can still improve this language to make it more general.

**Comment by mnm678** [comment]
Does anyone have the source for that image? @trishankatdatadog @jhdalek55

**Comment by jhdalek55** [comment]
I posted those images. It's in the assets file of the repo. These images were lifted from the Google Doc. I could probably play with it if I know what needs to be revised/changed.

**Comment by jhdalek55** [comment]
Can we get a judgement call here? I don't mind if we want to push this back to 1.2.0, but if the image is the only problem, I think I can fix it if I know what  needs to be changed.

**Comment by pattivacek** [comment]
I think we should push it to 1.2.0; it's not critical and I don't have the capacity to sort out the proper language at the moment.

**Comment by jhdalek55** [comment]
Unless there are any objections we will defer this to 1.2.0.

**Comment by jhdalek55** [comment]
Unless someone strongly objects in the next 24 hours, we will defer this to V.1.2.0

**Comment by jhdalek55** [comment]
Closed via PR #94
