### ISSUE TITLE
Introducing a secure software supply chain mechanism, such as in-toto, to Uptane

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#82]
At our last 2020 Standards meeting, the issue was raised that Uptane Deployment Best Practices should discuss options for securing the supply chain for automotive software. The Secure System Lab's in-toto project has already proven successful in integrating with TUF for such purposes. This issue thread can serve as a forum for discussing how to utilize the in-toto framework to minimize attack surfaces, and extend the protections of Uptane through the lifecycle of a piece of software.

**Comment by trishankatdatadog** [comment]
I think [ITE-2](https://github.com/in-toto/ITE/blob/master/ITE/2/README.adoc) and [ITE-3](https://github.com/in-toto/ITE/blob/master/ITE/3/README.adoc) should be decent start points for documentation on why and how to combine TUF and in-toto.

**Comment by jhdalek55** [comment]
@trishankatdatadog Do you think we could extract some starter text from those documents to begin playing with a PR on this issue? I think discussion is always better when we can put some text in play.

**Comment by jhdalek55** [comment]
Can someone take a run at developing some starter text for this issue? It is flagged for 2.0.0, but I think it would be helpful to put together a proposal for text on the Deployment pages. Even if we are not ready to propose an actual solution, I believe in the wake of SolarWinds, we should acknowledge that this is an issue we are investigating.

**Comment by jhdalek55** [comment]
This issue was discussed at some length at the 4/13/21 Uptane meeting. @JustinCappos recommended we look at the DataDog integration and/or software bill of materials (SBOM) entries. @iramcdonald pointed us towards the  NTIA Software Component Transparency (https://www.ntia.doc.gov/SoftwareTransparency).  We will be looking at various approaches and will add some copy to the Deployment pages on this topic.

**Comment by iramcdonald** [comment]
Hi Lois,

For NTIA, the primary reference should be to their SBOM (Software Bill of
Materials) project:

https://www.ntia.gov/SBOM

The other NTIA reference was to a related conference, but does not include
the list of tools,
formats, and standards for SBOMs (which *are* listed at the above
reference).

My TCG colleague Henk Birkholz (Fraunhofer Security Institute) is actively
participating in
the NTIA SBOM project.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Thanks for the update, Ira.

**Comment by trishankatdatadog** [comment]
[ITE-2](https://github.com/in-toto/ITE/blob/master/ITE/2/README.adoc) and [ITE-3](https://github.com/in-toto/ITE/blob/master/ITE/3/README.adoc) might help...

**Comment by jhdalek55** [comment]
As of the 8/3 Standards meeting, it was decided this topic will be addressed in our next whitepaper, which is to be released in December. Text will likely be added to the Deployment pages but possibly not in time for 2.0.0..

**Comment by jhdalek55** [comment]
Note that @trishankatdatadog  opened PURE Issue #2 dealing with this topic (https://github.com/uptane/pures/issues/2), so in parallel with the whitepaper he and @mnm678 will be drafting a PURE as well.

**Comment by jhdalek55** [comment]
Closing this via PR #121. I have left Issue #222 on the Standard page as a placeholder for additional thoughts on supply chain.
