### ISSUE TITLE
Are there more secure alternatives for ECU identifiers than supplier-name-prefixed serial numbers?

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#86]
Is there a better way of identifying ECUs that would be inherently more secure (and/or more flexible) than supplier-name-prefixed serial numbers? Given that not all ECUs share the same resources (as @iramcdonald observed, "an ECU that does nothing but adjust the seat belt does not need symmetric cryptography"), what does an identifier actually need to share? The text should reference IEEE 802.1AR Device ID (see https://1.ieee802.org/security/802-1ar/), a standard that specifies Secure Device Identifiers (DevIDs) designed to be used as interoperable secure device authentication credentials with Extensible Authentication Protocol (EAP) and other industry standard authentication and provisioning protocols. Stronger and clear text is needed as identity is too important to security to trust to just a part number.

**Comment by jhdalek55** [comment]
@iramcdonald...please add, delete or modify text for clarity.

**Comment by jhdalek55** [comment]
Can someone review this issue and recommend a strategy to address this issue. Also, I'm assuming this is a 2.0.0 issue, but can someone confirm this and mark it as such a milestone?

**Comment by iramcdonald** [comment]
Hi Lois,

Yes, this is definitely a v2.0.0 issue.

I still favor using IEEE 802.1AR Device Identity - which defines both
IDevIDs (immutable
manufacturer-supplied device identifiers) and LDevIDs (local device
identifiers generated by
a hash function from an IDevID and local network-specific context info -
these are mutable,
for example if a given ECU was moved from one vehicle to another vehicle).

TCG has new work-in-progress on TPM 2.0 Keys for Device Identity and
Attestation w/ device
certificates associated with IDevIDs and LDevIDs - coming to publication
soon.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
At our 4/13 meeting, it was agreed we should add an "Emerging Issues" page to Deployment Best Practices that would address topics like this one where no definitive solution is on the horizon. PR # 104 opened a file for this page and @jhdalek55 will draft some initial text. In addition to this issue, the text will address Issue #162, #200,  and #201 on the Standards page.

**Comment by jhdalek55** [comment]
Where are we at with this? We did include it in the Emerging Issues write-up, but how do we proceed with addressing the issue?

**Comment by jhdalek55** [comment]
It was decided at the 8/3 Uptane Standards meeting that a Deployment entry should be drafted that would address the concept of secure identifiers and would encompass both issues #86 and Issue #87. Ira McDonald also suggested that we review the Standard document and make sure that we do not imply anywhere in the document that a serial number by itself is a secure identifier.

**Comment by jhdalek55** [comment]
Issue #230 has been opened on the Standard issue as a reminder to make the necessary changes in policy once a clearer consensus on secure identifiers emerges. Therefore I am closing this issue and #87
