### ISSUE TITLE
Strategies for defining stronger software IDs

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#87]
We need to add text to the deployment pages that define methods for crafting stronger software Ids. This is  needed in the light of a proposed IETF Standard for Concise Software Identification Tags that is more secure than current supplier/OEM proprietary software version info. Concise SWID (CoSWID) tags, according to IETF's Datatracker  (https://datatracker.ietf.org/doc/draft-ietf-sacm-coswid/), "CoSWID supports a similar set of semantics and features as SWID tags, as well as new semantics that allow CoSWIDs to describe additional types of information, all in a more memory efficient format."

**Comment by jhdalek55** [comment]
@iramcdonald please add, change, delete above text.

**Comment by jhdalek55** [comment]
What do we need to complete this ?

**Comment by jhdalek55** [comment]
How can this be addressed? Can we clarify if this is a wording issue, and if so where and how do fix it?

**Comment by jhdalek55** [comment]
It was decided at the 8/3 Uptane Standards meeting that a Deployment entry should be drafted that would address the concept of secure identifiers and would encompass both issues #86 and #87. Ira McDonald also suggested that we review the Standard document and make sure that we do not imply anywhere in the document that a serial number by itself is a secure identifier.

**Comment by jhdalek55** [comment]
Since no one is stepping forward I can draft something that address #86 and #87 using the notes and references Ira provided in these threads. The text will be short and will mostly be a summary of why this is an issue that needs to be addressed. So I believe I can cobble something together for review and comment.

**Comment by iramcdonald** [comment]
Hi Lois,

Thanks for offering to draft the appropriate text.  I have no free cycles in
the near future.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
@iramcdinald as long as you and maybe one or two other can check the work I don't mind taking this on.

**Comment by jhdalek55** [comment]
Closing this issue and Issue #86 and re-opening a new issue on the Standard to make the necessary changes in policy once a clearer consensus on secure identifiers emerges (i.e.pending developments in evolving standards).
